version: '3.8'

services:
  # ---------- Angular Frontend ----------
  frontend:
    build:
      context: ./cxr-app
      dockerfile: Dockerfile
    image: my-angular-app:latest
    ports:
      - "4200:80"
    depends_on:
      - api


  # ---------- REST API Backend ----------
  api:
    build: ./REST_API
    image: my-rest-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
      # Add any other env vars your app needs


  # ---------- PostgreSQL Database ----------
  db:
    image: postgres:13
    platform: linux/amd64
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:

